# ~/.config/starship.toml

[character]
symbol = "ğŸ¦„"
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 6

[git_status]
style = "bold green"
